# Welcome to the main configuration file of ItemCreator ;p

# The default language file (under /langs/<code>.json)
# The actual file need to exist, else it will be by default en_US!
default_language: en_US

# Either creative player are allowed to bypass custom item restriction,
# such as can't craft, can't enchant, etc...
creative_bypass_restriction: true
