name: ItemCreator
version: '${version}'
main: info.itsthesky.itemcreator.ItemCreator
api-version: 1.13
authors: [ ItsTheSky ]
description: Create custom items easily using a simple in-game GUI.
commands:
  itemcreator:
    description: Base command for ItemCreator
    aliases:
      - ic
      - itemc
    permission: itemcreator.command